project:
  type: website

website:
  title: "leogau.dev"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/leogau
      - icon: twitter
        href: https://twitter.com/leogau
format:
  html:
    theme: cosmo
    css: styles.css
